# Generated by Django 5.0.2 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="max_players",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="court",
            name="operating_open_time",
            field=models.TimeField(default="06:00"),
        ),
        migrations.AddField(
            model_name="court",
            name="operating_close_time",
            field=models.TimeField(default="22:00"),
        ),
        migrations.AddField(
            model_name="court",
            name="blackout_dates",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
